Repository SBSystem/ESO, pull requests merged in 2018-03, with the labels that each got.

#3 Dodano kilka template
  config/routes.yaml
  src/AppBundle/TwigReturn/TwigTemplateReturn.php
  src/Command/CreateUserCommand.php
  src/Controller/Administrator/DashboardController.php
  src/Controller/Administrator/RoomController.php
  src/Entity/User.php
  src/Migrations/Version20180321141601.php
  templates/administrator/account/changePassword.html.twig
  templates/administrator/administration/rooms.html.twig
  templates/administrator/static/adminMenu.html.twig
  templates/administrator/tools/homeworkTemplate.html.twig
  templates/base.html.twig
Labels: help wanted

#9 [Basic] Zmieniono namespace dodano pierwszą stronę API
  config/routes.yaml
  src/Command/CreateUserCommand.php
  src/Controller/API/Administrator/Administration/EductionLevelAPI.php
  src/Controller/API/Administrator/EducationLevelAPI.php
  src/Controller/API/Interfaces/CRUD.php
Labels: Basic, Bug, Kernel, Status: Czeka na review

#10 [Frontend] Dodano css strony logowania
  public/css/main.css
  public/images/loginPageBg.jpg
  templates/index/login.html.twig
Labels: Status: Odrzucone, Status: Prowadzone są prace

#11 [API] Dodano pierwsze funkcje API
  src/Controller/API/Administrator/EducationLevelAPI.php
  src/Controller/API/Interfaces/CRUD.php
  src/Controller/index/LoginController.php
Labels: Basic, Status: Czeka na review, Ważne
